# Generated by Django 5.1.7 on 2026-05-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medicamento_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='aviso_estoque_minimo',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='estoque_atual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
