# Generated by Django 5.1.7 on 2026-09-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_medicamento_aviso_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromedicacao',
            name='quantidade_descontada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
